% this file read parameters from output file generated by svm_rank

function cc3 =readParam(output_file)
% output_file='/Users/zijunwei/Dev/CVPRIm/svm_rank/out.dat';
fid=fopen(output_file);

c=textscan(fid,'%s');
 i=65;
magicnum=109056;
tic
c_c=c{1}(i:end-1);
% cc=cellfun(@(x)x(3:end),c_c,'UniformOutput', false);
 cc2=cellfun(@(x)str2double(x),c_c,'UniformOutput', false);
 cc3=cell2mat(cc2);
toc
if length(cc3)~=magicnum
   cc3=zeros(magicnum,1);
   warning('%s is not coherent',output_file);
end
fclose(fid);